# @package model
type: rnn
attn: additive
emb_dim: 300
hidden: 512
num_layers: 2
teacher_forcing: 0.8
dropout: 0.1
src_emb: ./processed_data/zh_embedding_matrix.npy
tgt_emb: ./processed_data/en_embedding_matrix.npy