experiment: rnn-gru
seed: 42
device: cuda

data:
  dir: ./processed_data
  train_file: train.jsonl
  valid_file: valid.jsonl
  max_len: 50 # 预处理时设定的最大长度

model:
  type: rnn
  attn: additive          # dot | general | additive
  emb_dim: 300
  hidden: 256  # 编码器和解码器隐藏层维度 512，降一下维度
  dropout: 0.3
  num_layers: 2
  teacher_forcing: 0.6 # 训练时使用教师强制的概率 0.8 降低一下
  src_emb: ./processed_data/zh_embedding_matrix.npy
  tgt_emb: ./processed_data/en_embedding_matrix.npy

train:
  epochs: 100
  batch_size: 64
  lr: 0.001
  clip: 1.0
  # resume: ./runs/rnn-gru_rnn_additive_20251216_170754/last.pt  # 可选：恢复训练

wandb:
  enable: true
  project: nmt-course
  run_name: null  # 留空则自动使用目录名